Create branch from changes in fork

diff --git a/.github/workflows/ci-app2.yaml b/.github/workflows/ci-app2.yaml
--- a/.github/workflows/ci-app2.yaml
+++ b/.github/workflows/ci-app2.yaml
@@ -6,6 +6,7 @@ on:
       - 'main'
     paths:
       - 'apps/app2/**'
+
 jobs:
   docker:
     runs-on: ubuntu-latest
@@ -19,16 +20,42 @@ jobs:
       -
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      -
+      - 
         name: Login to DockerHub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
       -
-        name: Build and push app1
+        name: Get SemVer from file
+        id: semver-reader
+        uses: juliangruber/read-file-action@v1
+        with:
+          path: ./apps/app2/.version
+          
+      - name: Parse and Load SemVer
+        run: |
+          IFS='.'
+          read -a semver <<< ${{ steps.semver-reader.outputs.content }}
+          
+          if [ -z "${semver[0]}" ] || [ -z "${semver[1]}" ] || [ -z "${semver[2]}" ]; then # basic format check
+            echo "Error: Invalid semver format."
+            exit 1
+          fi
+          
+          echo "GITHUB_SHA_VALUE=`echo $GITHUB_SHA | cut -c 9- `" >> $GITHUB_ENV # setting patch semver version value
+          echo "V_MAJOR=${semver[0]}" >> $GITHUB_ENV # setting major semver version value 
+          echo "V_MINOR=${semver[1]}" >> $GITHUB_ENV # setting minor semver version value
+          echo "V_PATCH=${semver[2]}" >> $GITHUB_ENV # setting patch semver version value
+      - 
+        name: Build and push app2
         uses: docker/build-push-action@v3
         with:
           context: apps/app2/.
           push: true
-          tags: aandonov/app2:latest
+          tags: |
+            aandonov/app2:stage-v${{ env.V_MAJOR }}.${{ env.V_MINOR }}.${{ env.V_PATCH }}-${{ env.GITHUB_SHA_VALUE }}
+            aandonov/app2:latest        
+            
+            
